# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RACDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

#pod 'ReactiveObjC', '~> 3.1.0'
pod 'ReactiveViewModel', '~> 0.3'
pod 'SVProgressHUD'
pod 'AFNetworking', '~> 3.0'
pod 'YYModel'

  # Pods for RACDemo

end
