# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FunctionalProgramming' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'RXCollections', '~> 1.0'
  # Pods for FunctionalProgramming

end
